---
- name: Install Docker Compose
  hosts: all_vpn_servers
  gather_facts: yes
  become: yes

  roles:
    - docker_wireguard

- name: 1. Deploy Container Configuration Files
  hosts: endpoint_servers, edge_servers, vpc_servers, intermediate
  gather_facts: no
  become: no

  tasks:
    - name: Ensure base /opt/wireguard directory exists
      ansible.builtin.file:
        path: /opt/wireguard
        state: directory
        mode: '0755'
        owner: 'ubuntu'
        group: 'ubuntu'

    - name: Create base directory for WireGuard configs on remote VM
      ansible.builtin.file:
        path: /opt/wireguard/configs/
        state: directory
        mode: '0755'
        owner: 'ubuntu'
        group: 'ubuntu'

    - name: Create base directory for WireGuard client configs on remote VM
      ansible.builtin.file:
        path: /opt/wireguard/clients/
        state: directory
        mode: '0755'
        owner: 'ubuntu'
        group: 'ubuntu'
        
    - name: Copy the server WireGuard configuration file (wg_server_config_path)
      ansible.builtin.copy:
        src: "{{ wg_server_config_path }}"
        dest: "/opt/wireguard/configs/{{ wg_server_config_path | basename }}"
        mode: '0644'

    - name: Create base directory for bird  configs on remote VM
      ansible.builtin.file:
        path: /opt/wireguard/bird/
        state: directory
        mode: '0755'
        owner: 'ubuntu'
        group: 'ubuntu'
      become: yes

    - name: Copy the server bird configuration file (wg_bird_config_path)
      ansible.builtin.copy:
        src: "{{ wg_bird_config_path }}"
        dest: "/opt/wireguard/bird/{{ wg_bird_config_path | basename }}"
        mode: '0644'
        
    # - name: Copy the associated client configuration directory (if wg_clients_dir_path is set)
    #   ansible.builtin.copy:
    #     src: "{{ wg_clients_dir_path }}/" 
    #     dest: "/opt/wireguard/clients/{{ wg_server_config_path | basename | replace('.conf', '') }}/"
    #     mode: '0755'
    #   when: wg_clients_dir_path | length > 0

- name: 2. Deploy and Start Docker Compose Services
  hosts: all_vpn_servers
  gather_facts: no
  become: yes

  vars:
    unique_vms: "{{ groups['all_vpn_servers'] | map('extract', hostvars, 'ansible_host') | unique | list }}"

  tasks:
    - name: Copy the VM's Docker Compose file
      ansible.builtin.copy:
        src: "./{{ inventory_hostname }}_docker-compose.yml"
        dest: "/opt/wireguard/docker-compose.yml"
      when: inventory_hostname in unique_vms
      notify: Restart wireguard_container
      become: no 

    - name: Start / Restart services
      community.docker.docker_compose_v2:
        project_src: /opt/wireguard
        build: never
        state: present
      when: inventory_hostname in unique_vms

  handlers:
    - name: Restart wireguard_container
      community.docker.docker_compose_v2:
        project_src: /opt/wireguard
        build: never
        state: restarted
      when: inventory_hostname in unique_vms
